name: Fetch API and update data.json

on:
  schedule:
    # GitHub cron tối thiểu ~1 phút/lần; ví dụ 5 phút/lần:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: fetch-data
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch and write data.json
        env:
          API_URL: ${{ vars.API_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          node scripts/fetch.js

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi
          git commit -m "chore: update data.json"
          git push
